### ISSUE TITLE
Does it support two or more stores?

### ISSUE THREAD

**Issue by RomanKovalev** [assuncaocharles/react-indexed-db#5]
Can I create 2 stores with initDB?

If I create only one store, it works correctly:

```
export const DBConfig = {
    name: "SkiDB",
    version: 1,
    objectStoresMeta: [
        {
            store: 'activities',
            storeConfig: { keyPath: 'id', autoIncrement: true },
            storeSchema: [
               { name: 'type', keypath: 'type', options: { unique: false } }
            ]
        }
    ]
};
```

But when I add another store - the error raised.
Code:
```
initDB(DBConfig)
// DBConfig.js
export const DBConfig = {
    name: "SoundsDB",
    version: 1,
    objectStoresMeta: [
        {
            store: 'activities',
            storeConfig: { keyPath: 'id', autoIncrement: true },
            storeSchema: [
                { name: 'type', keypath: 'type', options: { unique: false } }
            ]
        },
        {
            store: 'utils',
            storeConfig: { keyPath: 'id', autoIncrement: true },
            storeSchema: [
                { name: 'sync_time', keypath: 'sync_time', options: { unique: false } }
            ]
        }
    ]
};
```

Error:

> main.js:formatted:14959 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Object.t.createTransaction (chrome-extension://ladepncaalkhmnlphdalcppfheapjghn/static/js/main.js:1:249689)
    at chrome-extension://ladepncaalkhmnlphdalcppfheapjghn/static/js/main.js:1:244572

**Comment by assuncaocharles** [comment]
Hi @RomanKovalev 

It works fine with 2 stores as you can see in the example bellow:

```js
import React from "react";
import ReactDOM from "react-dom";
import { initDB, useIndexedDB } from "react-indexed-db";

const DBConfig = {
  name: "MyDB",
  version: 1,
  objectStoresMeta: [
    {
      store: "people",
      storeConfig: { keyPath: "id", autoIncrement: true },
      storeSchema: [
        { name: "name", keypath: "name", options: { unique: false } },
        { name: "email", keypath: "email", options: { unique: false } }
      ]
    },
    {
      store: "animals",
      storeConfig: { keyPath: "id", autoIncrement: true },
      storeSchema: [
        { name: "name", keypath: "name", options: { unique: false } },
        { name: "email", keypath: "email", options: { unique: false } }
      ]
    }
  ]
};

initDB(DBConfig);

function App() {
  const { addPeople } = useIndexedDB("people");
  const { addAnimal } = useIndexedDB("animals");

  return (
    <React.Fragment>
      <button
        onClick={() => {
          addPeople({ name: "name", email: "email" }).then(
            event => {
              console.log("ID Generated: ", event.target.result);
            },
            error => {
              console.log(error);
            }
          );
        }}
      >
        add Animal
      </button>
      <button
        onClick={() => {
          addAnimal({ name: "name", email: "email" }).then(
            event => {
              console.log("ID Generated: ", event.target.result);
            },
            error => {
              console.log(error);
            }
          );
        }}
      >
        add People
      </button>
    </React.Fragment>
  );
}

ReactDOM.render(<App />, document.querySelector("#app"));

```

**Comment by RomanKovalev** [comment]
Thank you. Works too.

**Comment by meanking** [comment]
Hi @assuncaocharles 

I have tried your example but got this error.

![image](https://user-images.githubusercontent.com/49337840/134304844-9755f9f7-d2ea-4a5e-9492-24104b2ecb51.png)

```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Object.t.createTransaction (http://localhost:3000/static/js/vendors~main.chunk.js:317408:15)
    at http://localhost:3000/static/js/vendors~main.chunk.js:317102:23

pools:1 Uncaught (in promise) objectStore does not exists: animals
```
